### ISSUE TITLE
Publish container images with k promo to community owned infrastructure

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes-sigs/testgrid-json-exporter#1]
Currently, the images are getting promoted to quay.io this should be changed to push container images to community owned infrastructure

kpromo repo: https://github.com/kubernetes-sigs/promo-tools

How to publish container images: https://github.com/kubernetes-sigs/promo-tools/blob/main/docs/image-promotion.md

/kind feature

**Comment by leonardpahlke** [comment]
/assign @leonardpahlke 

@saschagrunert two, three questions: 
1. Should we run image promotion manually or as part of a GitHub actions pipeline? Note: running it automatically would require to create a PR to update the `images.yaml` file in the repo too ([doc](https://github.com/kubernetes-sigs/promo-tools/blob/main/docs/promotion-pull-requests.md#creating-promotion-pull-requests)). How do other (smaller) projects usually handle this? 
2. How can I “order” / create a community owned GCR repo?  

Thank you :)

**Comment by saschagrunert** [comment]
@leonardpahlke you need to get a staging repo in k8s.io to do that, for example like those PRs: https://github.com/kubernetes/k8s.io/pull/2640, https://github.com/kubernetes/k8s.io/pull/3792

Then you need a cloudbuild.yaml to build and push the images as postsubmit prow job, for example:
https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/cloudbuild.yaml

https://github.com/kubernetes/test-infra/blob/ee282aeafa084f0102feafe6c9404e0f8abf30bf/config/jobs/image-pushing/k8s-staging-security-profiles-operator.yaml

**Comment by leonardpahlke** [comment]
@saschagrunert the three PRs merged :) 

I believe there is one last step required to update the cluster judging this [comment](https://github.com/kubernetes/test-infra/pull/26729#issuecomment-1178794370), right.

> @leonardpahlke: Updated the `job-config` configmap in namespace `default` at cluster `test-infra-trusted` using the following files:
> * key `k8s-staging-tg-exporter.yaml` using file `config/jobs/image-pushing/k8s-staging-tg-exporter.yaml`

**Comment by saschagrunert** [comment]
@leonardpahlke I think you could merge a sample PR into main to see if the postsubmit works as intended. Or you trigger the cloudbuild manually via something like:

```
gcloud builds submit --verbosity info --config ./cloudbuild.yaml \
    --project k8s-staging-tg-exporter \
    --gcs-log-dir gs://k8s-staging-tg-exporter/logs \
    --gcs-source-staging-dir gs://k8s-staging-tg-exporter/source
```

The results should be available there afterwards: 
- https://console.cloud.google.com/storage/browser?project=k8s-staging-tg-exporter
- https://console.cloud.google.com/gcr/images/k8s-staging-tg-exporter
